### PR TITLE
Paper edits

### PR DESCRIPTION
**Pull request by mitchellpound**
Edits to the JOSS paper to make wording on line 40 clearer. Also added citations for Julia packages.

### CODE REVIEW

**Comment by lrnv** [comment]
Hey ! 

These changes to the package are perfect, thank you very much. 

Would you mind linking the PRs and the corresponding issues? You might do it by adding a closing sentence to the PR content (see there : https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue ) or on the right there is a link to do it. 

Then the issues will be automatically closed when the PR is merged, and I'll get a ping to take a look as you go.

**Comment by mitchellpound** [comment]
@lrnv, Thanks! Of course, I'll link all the issues now. I just wanted to give them another look over before sending you too many notifications.

**Comment by lrnv** [comment]
Thank you very much. 

This one looks great to me, nothing more to say.

**Review by Soclemens — APPROVED** [review]
LGTM

**Pull request merged**
